sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
  - 2.11.6
script:
  - cd play-2.4/swagger-play2 && sbt ++$TRAVIS_SCALA_VERSION compile test deploy
  - find $HOME/.sbt -name "*.lock" | xargs rm

jdk:
  - oraclejdk8
